--ex1
CREATE VIEW [Преподаватель]
 AS SELECT *
	FROM TEACHER

SELECT *
FROM Преподаватель
--ex2
CREATE VIEW [Количество кафедр]
AS
SELECT FACULTY.FACULTY_NAME,COUNT(PULPIT.PULPIT_NAME) AS [Количество]
FROM FACULTY INNER JOIN PULPIT
ON FACULTY.FACULTY=PULPIT.FACULTY
GROUP BY FACULTY.FACULTY_NAME

SELECT *
FROM [Количество кафедр]

SELECT * FROM AUDITORIUM
--ex3/4
CREATE VIEW [Аудитории]
as
SELECT AUDITORIUM.AUDITORIUM,AUDITORIUM.AUDITORIUM_TYPE
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_TYPE LIKE 'ЛК%' WITH CHECK OPTION

INSERT Аудитории (AUDITORIUM, AUDITORIUM_TYPE)
VALUES(309-2,'ЛБ-К')

INSERT Аудитории (AUDITORIUM, AUDITORIUM_TYPE)
VALUES(302-2,'ЛК')
--5
CREATE VIEW Дисциплины(Код, Наименование, Код_кафедры)
AS SELECT TOP 150 SUBJECT,SUBJECT_NAME,PULPIT
FROM SUBJECT
ORDER BY SUBJECT_NAME

SELECT * FROM Дисциплины
--ex6
ALTER VIEW [Количество кафедр] with SCHEMABINDING
AS SELECT FACULTY.FACULTY_NAME,COUNT(PULPIT.PULPIT_NAME) AS [Количество]
FROM dbo.FACULTY INNER JOIN dbo.PULPIT
ON FACULTY.FACULTY=PULPIT.FACULTY
GROUP BY FACULTY.FACULTY_NAME


select * from [Количество кафедр]