use UNIVER
SELECT AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE ON
AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE ON
AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE and 
	AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%'

SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME,PROFESSION.PROFESSION_NAME, SUBJECT.SUBJECT_NAME,STUDENT.NAME,
	case
        when PROGRESS.NOTE = 6 then 'шесть'
        when PROGRESS.NOTE = 7 then 'семь'
        when PROGRESS.NOTE = 8 then 'восемь'
        else 'Плохо'
    end as Оценки
FROM PROGRESS inner join STUDENT
	on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	inner join GROUPS 
	on GROUPS.IDGROUP=STUDENT.IDGROUP
	inner join PROFESSION on PROFESSION.PROFESSION=GROUPS.PROFESSION
	inner join SUBJECT on PROGRESS.SUBJECT=SUBJECT.SUBJECT
	inner join PULPIT on SUBJECT.PULPIT=PULPIT.PULPIT
	inner join FACULTY on PULPIT.FACULTY=FACULTY.FACULTY 
	where PROGRESS.NOTE between 6 and 8
	order by PROGRESS.NOTE

SELECT PULPIT.PULPIT as КАФЕДРА, isnull(TEACHER.TEACHER_NAME, '***') as ПРЕПОД
FROM PULPIT left outer join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT

select AUDITORIUM.AUDITORIUM,AUDITORIUM.AUDITORIUM_TYPE
	from AUDITORIUM_TYPE cross join AUDITORIUM
	where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE