SELECT TEACHER.TEACHER_NAME, PULPIT.PULPIT_NAME
FROM TEACHER INNER JOIN PULPIT
ON TEACHER.PULPIT=PULPIT.PULPIT
WHERE PULPIT.PULPIT_NAME ='Информационных систем и технологий '


SELECT TEACHER.TEACHER_NAME, FACULTY.FACULTY_NAME
FROM TEACHER INNER JOIN PULPIT
ON TEACHER.PULPIT=PULPIT.PULPIT
INNER JOIN FACULTY
ON PULPIT.FACULTY=FACULTY.FACULTY
WHERE FACULTY.FACULTY_NAME='Факультет информационных технологий'
AND TEACHER.TEACHER_NAME like '%и%'
order by TEACHER.TEACHER_NAME