use UNIVER
SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,
		MAX(AUDITORIUM.AUDITORIUM_CAPACITY)[Макс],
		MIN(AUDITORIUM.AUDITORIUM_CAPACITY)[Мин],
		AVG(AUDITORIUM.AUDITORIUM_CAPACITY)[Сред],
		SUM(AUDITORIUM.AUDITORIUM_CAPACITY)[Сумм],
		COUNT(AUDITORIUM.AUDITORIUM_CAPACITY)[Кол-во]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE 
ON AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	
SELECT *
FROM (
    SELECT CASE 
        WHEN PROGRESS.NOTE BETWEEN 4 AND 5 THEN '4-5'
        WHEN PROGRESS.NOTE BETWEEN 6 AND 7 THEN '6-7'
        WHEN PROGRESS.NOTE BETWEEN 6 AND 9 THEN '8-9'
        WHEN PROGRESS.NOTE = 10 THEN '10'
    END AS [Note],
    COUNT(*) AS [Count]
    FROM PROGRESS
    GROUP BY 
        CASE 
            WHEN PROGRESS.NOTE BETWEEN 4 AND 5 THEN '4-5'
            WHEN PROGRESS.NOTE BETWEEN 6 AND 7 THEN '6-7'
            WHEN PROGRESS.NOTE BETWEEN 6 AND 9 THEN '8-9'
            WHEN PROGRESS.NOTE = 10 THEN '10'
        END
) AS T
SELECT * FROM PROGRESS

SELECT A.FACULTY,G.PROFESSION,round(avg(cast(NOTE AS float(4))), 2) as [Средняя оценка]
FROM FACULTY AS A
INNER JOIN GROUPS G ON A.FACULTY=G.FACULTY
INNER JOIN STUDENT S ON S.IDGROUP=G.IDGROUP
INNER JOIN PROGRESS P ON P.IDSTUDENT=S.IDSTUDENT
WHERE P.SUBJECT='ОАиП' or P.SUBJECT='БД'
group by G.PROFESSION,A.FACULTY,G.IDGROUP

SELECT PR.PROFESSION_NAME,P.SUBJECT,AVG(P.NOTE) AS [Средняя]
FROM GROUPS AS G
INNER JOIN STUDENT S ON S.IDGROUP=G.IDGROUP
INNER JOIN PROGRESS P ON P.IDSTUDENT=S.IDSTUDENT
INNER JOIN PROFESSION PR ON PR.PROFESSION=G.PROFESSION
GROUP BY PR.PROFESSION_NAME,P.SUBJECT

select PROGRESS.SUBJECT, 
	   count(*) as [8, 9]
from PROGRESS 
group by PROGRESS.[SUBJECT], PROGRESS.NOTE
having PROGRESS.NOTE in (8,9)